class braf_ee9_cascavel_col: braf_ee9_cascavel_base
{
	scope=2;
	scopeCurator=2;
	side=2;
	faction="BRAF_FACTIONS";
	displayname="Colombian Army Engesa EE-9 Cascavel Mk3.";
	editorPreview="braf\braf_factions\addons\armored\data\cascavel\ui\EE-9_COL_picture_ca.paa";
	hiddenSelectionsTextures[]=
	{
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"braf\braf_factions\addons\armored\data\cascavel\COL1_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\COL2_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\Camo3_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\COL4_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\camonet_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\Glass_ca.paa"
	};	
	crew="braf_army_crewman_regular_2020";
	typicalcargo[]=
	{
		"braf_army_crewman_regular_2020",
		"braf_army_crewman_regular_2020"
	};	
};
class braf_ee9_cascavel_nia: braf_ee9_cascavel_base
{
	scope=2;
	scopeCurator=2;
	side=2;
	faction="BRAF_FACTIONS";
	displayname="New Iraq Army Engesa EE-9 Cascavel Mk3.";
	editorPreview="braf\braf_factions\addons\armored\data\cascavel\ui\EE-9_NIA_picture_ca.paa";
	animationList[]=
	{
		"showBackpacks",0,
		"showCamonetHull",1,
		"showCamonetCannon",1
	};
	hiddenSelectionsTextures[]=
	{
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"braf\braf_factions\addons\armored\data\cascavel\New_Iraq1_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\New_Iraq2_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\Camo3_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\New_Iraq4_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\Tan_camonet_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\Glass_ca.paa"
	};	
	crew="braf_army_crewman_regular_2020";
	typicalcargo[]=
	{
		"braf_army_crewman_regular_2020",
		"braf_army_crewman_regular_2020"
	};	
};
class braf_ee9_cascavel_iran: braf_ee9_cascavel_base
{
	scope=2;
	scopeCurator=2;
	side=2;
	faction="BRAF_FACTIONS";
	displayname="Iran Army Engesa EE-9 Cascavel Mk3.";
	editorPreview="braf\braf_factions\addons\armored\data\cascavel\ui\EE-9_IRAN_picture_ca.paa";
	animationList[]=
	{
		"showBackpacks",0,
		"showCamonetHull",1,
		"showCamonetCannon",1
	};
	hiddenSelectionsTextures[]=
	{
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"braf\braf_factions\addons\armored\data\cascavel\IRAN1_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\IRAN2_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\Camo3_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\IRAN4_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\Tan_camonet_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\Glass_ca.paa"
	};	
	crew="braf_army_crewman_regular_2020";
	typicalcargo[]=
	{
		"braf_army_crewman_regular_2020",
		"braf_army_crewman_regular_2020"
	};	
};
class braf_ee9_cascavel_oia: braf_ee9_cascavel_nia
{
	displayname="Old Iraq Army Engesa EE-9 Cascavel Mk3.";
	editorPreview="braf\braf_factions\addons\armored\data\cascavel\ui\EE-9_OIA_picture_ca.paa";
	hiddenSelectionsTextures[]=
	{
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"braf\braf_factions\addons\armored\data\cascavel\Old_Iraq1_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\Old_Iraq2_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\Camo3_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\Old_Iraq4_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\Tan_camonet_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\Glass_ca.paa"
	};	
	crew="braf_army_crewman_regular_2020";
	typicalcargo[]=
	{
		"braf_army_crewman_regular_2020",
		"braf_army_crewman_regular_2020"
	};
};
class braf_ee9_cascavel_hiaf: braf_ee9_cascavel_base
{
	scope=2;
	scopeCurator=2;
	side=1;
	faction = "BRAF_HIAF";
	displayname="Engesa EE-9 Cascavel Mk3.";
	editorPreview="braf\braf_factions\addons\armored\data\cascavel\ui\EE-9_HIAF_picture_ca.paa";
	hiddenSelectionsTextures[]=
	{
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"braf\braf_factions\addons\armored\data\cascavel\HIAF1_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\HIAF2_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\Camo3_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\HIAF4_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\camonet_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\Glass_ca.paa"
	};	
	crew="braf_horizon_regular";
	typicalcargo[]=
	{
		"braf_horizon_regular",
		"braf_horizon_regular"
	};
};
class braf_ee9_cascavel_putain: braf_ee9_cascavel_hiaf
{
	displayname="Engesa EE-9 Cascavel Mk3.";
	editorPreview="braf\braf_factions\addons\armored\data\cascavel\ui\EE-9_PUTAIN_picture_ca.paa";
	hiddenSelectionsTextures[]=
	{
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"braf\braf_factions\addons\armored\data\cascavel\PUTAIN1_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\PUTAIN2_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\Camo3_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\HIAF4_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\camonet_co.paa",
		"braf\braf_factions\addons\armored\data\cascavel\Glass_ca.paa"
	};
};